name: Appium Kotlin Tests

on:
  workflow_dispatch:
    inputs:

      testClass:
        description: Select Test Class
        required: true
        type: choice
        options:
          - AndroidAppAutomation
          - AndroidWebAutomation
          - IOSAppAutomation
          - IOSWebAutomation

      platform:
        description: Select Platform
        required: true
        type: choice
        options:
          - android
          - ios
          - both

jobs:

  run-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: ${{ fromJson(github.event.inputs.platform == 'both' && '["android","ios"]' || format('["{0}"]', github.event.inputs.platform)) }}

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11

      - run: mvn clean install -DskipTests

      - run: |
          echo "Running ${{ github.event.inputs.testClass }} on ${{ matrix.platform }}"
          mvn -Dtest=${{ github.event.inputs.testClass }} test